### ISSUE TITLE
为什么我安装了这个主题，图片显示不了

### ISSUE THREAD

**Issue by Youclose** [spiritree/typecho-theme-amaze#19]
Catchable fatal error: Argument 1 passed to Widget_Abstract_Contents::size() must be an instance of Typecho_Db_Query, null given, called in D:\localuser\ftp62549823\Web\var\Widget\Archive.php on line 565 and defined in D:\localuser\ftp62549823\Web\var\Widget\Abstract\Contents.php on line 594

**Comment by spiritree** [comment]
无法复现，有更具体的信息吗

**Comment by Youclose** [comment]
抱歉，是我的服务器问题，已经解决。
